version: '3.3'
services:
  service2:
    image: service2
    container_name: service2
    build:
      context: ./flask-service-2
      dockerfile: Dockerfile
    ports: 
    - target: 5001
      published: 5001
  service3:
    image: service3
    container_name: service3
    build:
      context: ./flask-service-3
      dockerfile: Dockerfile
    ports:
      - target: 5002
        published: 5002


        #    service3:
        #      build:
        # context: ./service3
        # dockerfile: Dockerfile
