version: '3.3'
services:
  service1:
    image: indpro2-jen:5000/service1:build-${BUILD_NUMBER}
    container_name: service1
    build:
      context: ./flask-service-1
      dockerfile: Dockerfile
    environment:
    - MYSQL_DB_TEST=${MYSQL_DB_TEST}
    - MYSQL_KEY=${MYSQL_KEY}
    - MYSQL_DB=${MYSQL_DB}
    - MYSQL_URL=${MYSQL_URL}
    - MYSQL_PASS=${MYSQL_PASS}
    - MYSQL_USER=${MYSQL_USER}
    ports:
    - target: 5000
      published: 5000
  service2:
    image: indpro2-jen:5000/service2:build-${BUILD_NUMBER}
    container_name: service2
    build:
      context: ./flask-service-2
      dockerfile: Dockerfile
    ports: 
    - target: 5001
      published: 5001
  service3:
    image: indpro2-jen:5000/service3:build-${BUILD_NUMBER}
    container_name: service3
    build:
      context: ./flask-service-3
      dockerfile: Dockerfile
    ports:
      - target: 5002
        published: 5002
  service4:
    image: indpro2-jen:5000/service4:build-${BUILD_NUMBER}
    container_name: service4
    build:
      context: ./flask-service-4
      dockerfile: Dockerfile
    ports:
      - target: 5003
        published: 5003

        #    service3:
        #      build:
        # context: ./service3
        # dockerfile: Dockerfile
